dist: focal
sudo: required

services:
  - docker

language:
  - ruby
rvm:
  - 2.6.6

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.28.6
    - DOCKER_BUILDX_VERSION=0.5.1
    - PUPPETSERVER_IMAGE=puppet/puppetserver:edge

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl --location https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname --kernel-name`-`uname --machine` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - mkdir -vp ~/.docker/cli-plugins
  - curl --location https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
  - chmod +x ~/.docker/cli-plugins/docker-buildx


# Use --fail-fast so if the cluster fails to come up successfully we don't need
# to wait for every service to time out
script:
  - bundle exec rspec spec --fail-fast
