sudo: required

services:
  - docker

language:
  - ruby
rvm:
  - 2.5.5

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.0-rc2
    - PRELOAD_CERTS=1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl --location https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname --kernel-name`-`uname --machine` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make test
