version: '3.7'
services:
  puppet:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-puppetserver:kearney-latest
    hostname: puppet.test
    environment:
      - PUPPETDB_HOSTNAME=puppetdb.test
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
    ports:
      - 8140:8140
    dns_search: test
    networks:
      test:
        aliases:
         - puppet.test
  pe-orchestration-services:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-orchestration-services:kearney-latest
    hostname: pe-orchestration-services.test
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_HOSTNAME=puppetdb.test
      - POSTGRES_HOSTNAME=postgres.test
      - PE_BOLT_SERVER_HOSTNAME=pe-bolt-server.test
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
    ports:
      - 8142:8142
      - 8143:8143
    depends_on:
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
         - pe-orchestration-services.test
  pe-console-services:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-console-services:kearney-latest
    hostname: pe-console-services.test
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_HOSTNAME=puppetdb.test
      - POSTGRES_HOSTNAME=postgres.test
      - PE_ORCHESTRATION_SERVICES_HOSTNAME=pe-orchestration-services.test
    ports:
      - 443:4431
      - 4430:4430
      - 4432:4432
      - 4433:4433
    depends_on:
      - postgres
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
          - pe-console-services.test
  pe-bolt-server:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-bolt-server:kearney-latest
    hostname: pe-bolt-server.test
    expose:
      - 62658
      - 62659
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PE_BOLT_SERVER_LOGLEVEL=${PE_BOLT_SERVER_LOGLEVEL:-info}
    networks:
      test:
        aliases:
          - pe-bolt-server.test
  puppetdb:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-puppetdb:kearney-latest
    hostname: puppetdb.test
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_POSTGRES_HOSTNAME=postgres.test
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
          - puppetdb.test
  postgres:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-postgres
    hostname: postgres.test
    environment:
      - CERTNAME=postgres.test
      - PUPPETSERVER_HOSTNAME=puppet.test
    expose:
      - 5432
    dns_search: test
    networks:
      test:
        aliases:
          - postgres.test
  puppet-agent:
    image: puppet/puppet-agent-ubuntu:6.4.2
    hostname: puppet-agent.test
    networks:
      test:
        aliases:
          - puppet-agent.test
    entrypoint: /bin/bash
    command: -c "echo 'waiting for orchestration services to be up' &&
                 while true; sleep 5; do if curl -k --fail --silent https://pe-orchestration-services.test:8143/status/v1/simple; then break; fi; done &&
                 puppet config set server puppet.test &&
                 puppet agent -t &&
                 echo 'starting pxp services' &&
                 pxp-agent --broker-ws-uri wss://pe-orchestration-services.test:8142/pcp2/
                           --ssl-ca-cert /etc/puppetlabs/puppet/ssl/certs/ca.pem
                           --ssl-cert /etc/puppetlabs/puppet/ssl/certs/puppet-agent.test.pem
                           --ssl-key /etc/puppetlabs/puppet/ssl/private_keys/puppet-agent.test.pem
                           --pcp-version 2"
  test-sshd:
    image: rastasheep/ubuntu-sshd:18.04
    expose:
      - 22
    networks:
      - test
    networks:
      test:
        aliases:
          - test_sshd.test
networks:
  test:
    name: pupperware-commercial
