version: '3.7'
services:
  puppet:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-puppetserver:kearney-latest
    hostname: puppet.test
    environment:
      - CERTNAME=puppet.test
      - PUPPETDB_HOSTNAME=puppetdb.test
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
      - PE_ORCHESTRATION_SERVICES_HOSTNAME=pe-orchestration-services.test
      # Set the control repo URL like https://github.com/puppetlabs/control-repo.git
      # For private repos, use git@github.com:user/repo.git and provide SSH keys
      # - R10K_REMOTE=
    volumes:
      - puppetserver:/opt/puppetlabs/server/data/puppetserver
      - puppetserver-packages:/opt/puppetlabs/server/data/packages
      - code-manager:/opt/puppetlabs/server/data/code-manager
      # NOTE: for an R10K_REMOTE the id-control_repo.rsa path may be bind mounted like:
      # - ./path/to/codemanager/ssh:/etc/puppetlabs/puppetserver/ssh
      # Additional SSH configuration files may be placed in this directory
    ports:
      - 8140:8140
      - 8170:8170
    dns_search: test
    networks:
      test:
        aliases:
         - puppet.test
  pe-orchestration-services:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-orchestration-services:kearney-latest
    hostname: pe-orchestration-services.test
    environment:
      - CERTNAME=pe-orchestration-services.test
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_HOSTNAME=puppetdb.test
      - POSTGRES_HOSTNAME=postgres.test
      - PE_BOLT_SERVER_HOSTNAME=pe-bolt-server.test
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
      - PUPPERWARE_ADMIN_PASSWORD=pupperware
    volumes:
      - orchestration-services:/opt/puppetlabs/server/data/orchestration-services
    ports:
      - 8142:8142
      - 8143:8143
    depends_on:
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
         - pe-orchestration-services.test
  pe-console-services:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-console-services:kearney-latest
    hostname: pe-console-services.test
    environment:
      - CERTNAME=pe-console-services.test
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETSERVER_CERTNAME=puppet.test
      - PUPPETDB_HOSTNAME=puppetdb.test
      - PUPPETDB_CERTNAME=puppetdb.test
      - POSTGRES_HOSTNAME=postgres.test
      - PE_ORCHESTRATION_SERVICES_HOSTNAME=pe-orchestration-services.test
      - PE_ORCHESTRATION_SERVICES_CERTNAME=pe-orchestration-services.test
    volumes:
      - console-services:/opt/puppetlabs/server/data/console-services
    ports:
      - 443:4431
      - 4430:4430
      - 4432:4432
      - 4433:4433
    depends_on:
      - postgres
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
          - pe-console-services.test
  pe-bolt-server:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-bolt-server:kearney-latest
    hostname: pe-bolt-server.test
    expose:
      - 62658
      - 62659
    environment:
      - CERTNAME=pe-bolt-server.test
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PE_BOLT_SERVER_LOGLEVEL=${PE_BOLT_SERVER_LOGLEVEL:-info}
      - WHITELIST_HOSTNAME.0=pe-bolt-server.test
      - WHITELIST_HOSTNAME.1=pe-orchestration-services.test
    volumes:
      - bolt-server:/opt/puppetlabs/server/data/bolt-server
    networks:
      test:
        aliases:
          - pe-bolt-server.test
  puppetdb:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-puppetdb:kearney-latest
    hostname: puppetdb.test
    environment:
      - CERTNAME=puppetdb.test
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_POSTGRES_HOSTNAME=postgres.test
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services.test
    volumes:
      - puppetdb:/opt/puppetlabs/server/data/puppetdb
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - postgres
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
          - puppetdb.test
  postgres:
    image: artifactory.delivery.puppetlabs.net/pe-and-platform/pe-postgres
    hostname: postgres.test
    environment:
      - CERTNAME=postgres.test
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPETDB_CERTNAME=puppetdb.test
      - PE_CONSOLE_SERVICES_CERTNAME=pe-console-services.test
      - PE_ORCHESTRATION_SERVICES_CERTNAME=pe-orchestration-services.test
    volumes:
      - puppetdb-postgres:/var/lib/postgresql/data
    expose:
      - 5432
    depends_on:
      - puppet
    dns_search: test
    networks:
      test:
        aliases:
          - postgres.test
networks:
  test:
    name: pupperware-commercial
volumes:
  puppetserver:
  puppetserver-packages:
  code-manager:
  orchestration-services:
  console-services:
  bolt-server:
  puppetdb:
  puppetdb-postgres:
