version: '3.7'
services:
  pe-orchestration-services:
    image: artifactory.delivery.puppetlabs.net/platform-services-297419/pe-and-platform/pe-orchestration-services:latest
    hostname: pe-orchestration-services
    environment:
      - CERTNAME=pe-orchestration-services
      # NOTE: Java follows RFC 2818 stating when SAN is provided, it's authoritative / Subject should be ignored
      - DNS_ALT_NAMES=pe-orchestration-services
      - PCP_BROKER_PORT=8142
      - PE_ORCHESTRATION_SERVICES_PORT=8143
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_HOSTNAME=puppetdb
      - PUPPETDB_SSL_PORT=8081
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - PE_BOLT_SERVER_HOSTNAME=pe-bolt-server
      - PE_CONSOLE_SERVICES_HOSTNAME=pe-console-services
      - ADMIN_RBAC_PASSWORD=pupperware
    volumes:
      - orchestration-services:/opt/puppetlabs/server/data/orchestration-services
    restart: always
    ports:
      - 8142:8142
      - 8143:8143

  pe-console-services:
    image: artifactory.delivery.puppetlabs.net/platform-services-297419/pe-and-platform/pe-console-services:latest
    hostname: pe-console-services
    environment:
      - CERTNAME=pe-console-services
      # NOTE: Java follows RFC 2818 stating when SAN is provided, it's authoritative / Subject should be ignored
      - DNS_ALT_NAMES=pe-console-services
      - PE_CONSOLE_SERVICES_LOG_LEVEL=info
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_HOSTNAME=puppetdb
      - PUPPETDB_SSL_PORT=8081
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - PE_ORCHESTRATION_SERVICES_HOSTNAME=pe-orchestration-services
      - PE_ORCHESTRATION_SERVICES_PORT=8143
      - RBAC_CERTIFICATE_ALLOWLIST=puppet,puppetdb,pe-orchestration-services
    volumes:
      - console-services:/opt/puppetlabs/server/data/console-services
    restart: always
    ports:
      - 443:4431
      - 4433:4433
    expose:
      - 4430
      - 4432

  pe-bolt-server:
    image: artifactory.delivery.puppetlabs.net/platform-services-297419/pe-and-platform/pe-bolt-server:latest
    hostname: pe-bolt-server
    restart: always
    expose:
      - 62658
    environment:
      - CERTNAME=pe-bolt-server
      # NOTE: Java follows RFC 2818 stating when SAN is provided, it's authoritative / Subject should be ignored
      - DNS_ALT_NAMES=pe-bolt-server
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PE_BOLT_SERVER_LOGLEVEL=${PE_BOLT_SERVER_LOGLEVEL:-info}
      - WHITELIST_HOSTNAME.0=pe-bolt-server
      - WHITELIST_HOSTNAME.1=pe-orchestration-services
    volumes:
      - bolt-server:/opt/puppetlabs/server/data/bolt-server

networks:
  default:
    name: pupperware-commercial
volumes:
  orchestration-services:
  console-services:
  bolt-server:
